#!/bin/bash

# Run as root or sudo user
if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root or with sudo privileges."
  exit 1
fi

# Identify Linux distribution
linux_distribution=$(grep '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')

# Set default file paths and variables
bareos_script_path="/tmp/add_bareos_repositories.sh"
tls_url="https://box110.exaservers.com/tls.tar.gz"
tls_dest="/tmp/tls.tar.gz"

# Download and configure Bareos repository based on the distribution
case $linux_distribution in
  centos)
     wget -O $bareos_script_path "https://download.bareos.org/current/EL_7/add_bareos_repositories.sh"
    ;;
  rocky | almalinux | cloudlinux)
    wget -O $bareos_script_path "https://download.bareos.org/current/EL_8/add_bareos_repositories.sh"
    ;;
  ubuntu)
    wget -O $bareos_script_path "https://download.bareos.org/current/xUbuntu_20.04/add_bareos_repositories.sh"
    ;;
  *)
    echo "Unsupported distribution: $linux_distribution"
    exit 1
    ;;
esac

# Change permission for the Bareos script file
chmod 0755 $bareos_script_path

# Run the script to add the repository
bash $bareos_script_path

# Update package cache and install Bareos File Daemon
if [[ "$linux_distribution" =~ ^(centos|rocky|almalinux|cloudlinux)$ ]]; then
  yum update -y
  yum install -y bareos-fd
elif [ "$linux_distribution" == "ubuntu" ]; then
  apt-get update
  apt-get install -y bareos
fi

# Configure Bareos Client and Director settings
cat > /etc/bareos/bareos-fd.d/client/myself.conf <<EOL
# Insert content of the client.conf.j2 template here
EOL

cat > /etc/bareos/bareos-fd.d/director/bareos-dir.conf <<EOL
# Insert content of the director.conf.j2 template here
EOL

# Download and extract TLS files
wget -O $tls_dest $tls_url
tar -xzvf $tls_dest -C /etc/bareos/

# Set ownership of Bareos directory
chown -R bareos:bareos /etc/bareos/

# Restart Bareos File-Daemon
systemctl restart bareos-fd
