#!/bin/bash

NEW_PASSWORD="value"
while IFS= read -r email; do
    if [[ ! "$email" =~ "@" ]]; then
        continue
    fi
    uapi --user=username Email passwd_pop email="$email" password="$NEW_PASSWORD"
    echo "Updated password for $email"
done < email_list.txt
